#!/bin/bash
cat - <<EOF
tmuxify [./tmuxify.sh] <command>

Runs tmuxify, managing a tmux server at TMUX_SOCKET running
the scripts in the SITE_PANES directory.

attach     Attaches to the existing tmux server, if any.
cmd        Runs a tmux command
env        Dumps the site environment used by tmuxify
create     Creates a new tmux window for the project.
is-running Returns true and exits zero if the server is running
stop       Stops the site and closes the tmux server
open       Opens a browser window to the root site
restart    Restarts the site
start      Starts the site if it's not running, attaches, and opens a window
kill       Alias for kill

tmuxify.sh variables:
SITE_NAME   name of the site
SITE_PATH   path to the site
SITE_PANES  path containing site's scripts to run
TMUX        path to tmux executable
TMUX_SOCKET path to tmux server socket
SITE_PORT   optional, port to use for tmuxify open
EOF
