#!/bin/bash
cat - <<EOF
tmuxify [./tmuxify.sh] <command>

Runs tmuxify, managing a tmux window running the scripts in the SITE_PANES
directory.

start      Starts the site if it's not running, attaches, and opens a window
restart    Restarts the site
stop       Stops the site and closes the tmux server
attach     Attaches to the existing tmux server, if any.
open       Opens a browser window to the root site
is-running Returns true and exits zero if the server is running
cmd        Runs a tmux command
env        Dumps the site environment used by tmuxify

tmuxify.sh variables:
SITE_NAME   name of the site (default: $(basename `pwd`))
SITE_PATH   path to the site (default: `pwd`)
SITE_PANES  optional, path containing site's scripts to run (default: `pwd`/panes)
TMUX        optional, path to tmux executable (default: `which tmux`)
TMUX_SOCKET optional, path to custom tmux server socket (default: user's default socket)
SITE_PORT   optional, port to use for tmuxify open (default is undefined)
EOF
