#!/bin/bash
source $TMUXIFY_ROOT/functions.sh || exit

if test $# -gt 0; then
    SITE_PORT=$1
    shift
fi
test -n "$SITE_PORT" || die "SITE_PORT is not defined"
xdg-open https://`hostname`:$SITE_PORT &>/dev/null
