#!/bin/bash
source $TMUXIFY_ROOT/functions.sh || exit

if test $# -gt 0; then
    SITE_PORT=$1
    shift
fi
test -n "$SITE_PORT" || exit

if echo $SITE_URL | grep -q -E -e '/$'; then
URL="$SITE_URL"
else
URL="$SITE_URL:$SITE_PORT"
fi

TRIES=3
while test $TRIES -gt 0 && ! curl -k --fail-with-body $URL &>/dev/null; do
    sleep 1
    let TRIES--
done
xdg-open $URL &>/dev/null
