#!/bin/bash
source $TMUXIFY_ROOT/functions.sh || exit

if test $# -gt 0; then
    SITE_PORT=$1
    shift
fi
test -n "$SITE_PORT" || die "SITE_PORT is not defined"

URL="$SITE_URL:$SITE_PORT"
TRIES=30
while test $TRIES -gt 0 && ! curl -k --fail-with-body $URL &>/dev/null; do
    sleep 1
    let TRIES--
done
xdg-open $URL &>/dev/null
